name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build release for Alpine
      run: cargo build --release --target x86_64-unknown-linux-musl
    - name: Build container
      run: docker build --tag who_dat_kid:$GITHUB_SHA .
